---
ec2_access_key: "--REMOVED--"
ec2_secret_key: "--REMOVED--"

# ami_id: "ami-3bfab942"
ami_id: "ami-bfb5fec6"
ecsInstancesCount: 1

# jenkinsDockerImage: "483149632405.dkr.ecr.eu-west-1.amazonaws.com/fileshare:release-v1.0-71"
jenkinsDockerImage: "483149632405.dkr.ecr.eu-west-1.amazonaws.com/jenkins:latest"
...