---
- name: Create Docker image
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        name: "{{ item.repository.repositoryUri }}"
        path: .
        tag: latest
        state: present
        push: yes
      with_items: "{{ ecr.results }}"
      register: docker_image

    # - name: Build image and with buildargs
    #   docker_image:
    #     dockerfile: ./Dockerfile
    #     path: /home/set/Downloads/cicd01/
    #     name: myimage
    #     buildargs:
    #       log_volume: /var/log/myapp
    #       listen_port: 8080

    - name: docker_image
      debug:
        msg: "{{ item.invocation.module_args.name }}:{{ item.invocation.module_args.tag }}"
      with_items: "{{ docker_image.results }}"
  
...