---
- name: Instances creation play
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Provision a set of instances
      ec2:
        #aws_access_key: "{{ec2_access_key}}"
        #aws_secret_key: "{{ec2_secret_key}}"
        region: eu-west-1
        key_name: KeyPair01
        group: WebServerSG
        instance_type: t2.micro
        image: "{{ ami_id }}"
        instance_profile_name: ecsInstanceRole
        exact_count: 2
        count_tag:
          cluster: default
        instance_tags:
          cluster: default
        # user_data: 'sudo sh -c "echo ECS_CLUSTER=cluster01 >> /etc/ecs/ecs.config"'
        wait: true
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: no
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"

- name: Instances configuration play
  hosts: ec2hosts  
  user: ec2-user
  become: true
  gather_facts: true

  tasks:
    #  - name: Configure ECS cluster
    #    become: true
    #    shell: echo ECS_CLUSTER=cluster01 >> /etc/ecs/ecs.config
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

...