---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a set of instances
      ec2:
        #aws_access_key: "{{ec2_access_key}}"
        #aws_secret_key: "{{ec2_secret_key}}"
        region: eu-west-1
        key_name: KeyPair01
        group: WebServerSG
        instance_type: t2.micro
        image: "{{ ami_id }}"
        exact_count: 5
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
        wait: true
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 20
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:
     - name: Check NTP service
       service: name=ntpd state=started
...