---
- name: ECS creation play
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    # Cluster creation
    - ecs_cluster:
        name: "{{ item }}"
        state: present
      loop:
        - default
        # - cluster01

    # # Cluster deletion
    # - ecs_cluster:
    #     name: default
    #     state: absent

    # - name: Wait for register
    #   ecs_cluster:
    #     name: "{{ new_cluster }}"
    #     state: has_instances
    #     delay: 10
    #     repeat: 10
    #   register: task_output

    - name: Create task definition
      ecs_taskdefinition:
        containers:
        - name: jenkinsContainer
          essential: true
          # image: "{{ jenkinsDockerImage }}"
          image: "{{ item.invocation.module_args.name }}:{{ item.invocation.module_args.tag }}"
          memory: 256
          portMappings:
          - containerPort: 8080
            hostPort: 8080
        family: jenkinsFamily
        state: present
      with_items: "{{ docker_image.results }}"
      register: task_output

    # - name: Task output
    #   debug: var=task_output.taskdefinition.containerDefinitions

    - name: Run task
      ecs_task:
        operation: run
        cluster: default
        task_definition: jenkinsFamily
        count: 1
        started_by: ansible
      register: task_output

    # - name: Task output
    #   debug: var=task_output
...