---
- name: ECS creation play
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    # Cluster creation
    - ecs_cluster:
        name: "{{ item }}"
        state: present
      loop:
        - default
        # - cluster01

    # # Cluster deletion
    # - ecs_cluster:
    #     name: default
    #     state: absent

    # - name: Wait for register
    #   ecs_cluster:
    #     name: "{{ new_cluster }}"
    #     state: has_instances
    #     delay: 10
    #     repeat: 10
    #   register: task_output

    - name: Create task definition
      ecs_taskdefinition:
        containers:
        - name: jenkinsTask
          essential: true
          image: "483149632405.dkr.ecr.eu-west-1.amazonaws.com/fileshare:release-v1.0-71"
          memory: 256
          portMappings:
          - containerPort: 80
            hostPort: 80

        family: jenkinsFamily
        state: present
      register: task_output
...