---
# If the repository does not exist, it is created. If it does exist, would not
# affect any policies already on it.

- name: Create some ECRs
  ecs_ecr: 
    name: "{{ item }}"
    state: present
  loop:
    - "{{ ecr_name }}"
  register: ecr

# - name: Remove some ECRs
#   ecs_ecr: 
#     name: "{{ item }}"
#     state: absent
#   loop:
#     - deleted/ecr

- name: ecr
  debug: 
    msg: "repositoryUri: {{ item.repository.repositoryUri }}"
  with_items: "{{ ecr.results }}"
